MACCONNELL:
  # This application was originally developed for a particular set of historical images known as the MacConnell set.
  # Some assumptions can be made due to what we know about this data that allows for specialized definitions in this
  # config file. If you are using this application for another purpose or on another set of images, set 'USE' to 'False'
  # and fill out 'OTHER'. Only one of 'MACCONNELL' or 'OTHER' needs to be filled out correctly.
  USE: True
  INPUT:
    # This is the image code dpb6h109, cni1h111, etc. of the MANUALLY georeferenced image.
    REF_CODE: cni3h80
    # The MacConnell images that overlap this image that you wish to georeference.
    OVERLAPPING_CODES: cni3h81
    # The folder containing referenced MacConnell images.
    REF_PATH: D:/MacConnell/Photos_Georeferenced_Samples/
    # The folder containing un-referenced MacConnell images.
    UNREF_PATH: D:/MacConnell/Photos_Original/
    # Your initials to place in the GCP.txt filename.
    INITIALS: CG
    # The maximum number of potential GCPs you would like to see for each image.
    MAX_GCPS: 25

  OUTPUT:
    # The location to save the GCP txt file to.
    GCP_OUTPUT_LOC: D:/MacConnell/Final/GCPs/
    # The location to save the georeferenced TIFF file to.
    REF_OUTPUT_LOC: D:/MacConnell/Final/Georeferenced/


OTHER:
  INPUT:
    # The path to the referenced source image.
    REF_PATH: D:/MacConnell/Photos_Georeferenced_Samples/mufs190-1952-cni3h80-i001.reference.tif
    # The path to the un-referenced overlapping images.
    UNREF_PATHS: D:/MacConnell/Photos_Original/b005/mufs190-1952-cni3h81-i001-001.tif
    # The maximum number of potential GCPs you would like to see for each image.
    MAX_GCPS: 25
    # The DPI of the unreferenced images. Needed to write the GCP text file in correct units.
    DPI: 600
    # The EPSG code that the resulting georeferenced image will be in.
    EPSG: 26986

    # ALGORITHM PARAMETERS

    # The dimensions to scale the images to in preprocessing.
    X_SCALE: 600
    Y_SCALE: 600
    # The RANSAC threshold. Larger numbers will make inliers more uniform and sparse
    RANSAC_THRESHOLD: 5
    # The size of the grid surrounding each pixel used in Harris Corner Detection. Increase if your images are low
    # quality, or you want to detect larger corners.
    BLOCK_SIZE: 2
    # The size of the Sobel aperture kernel. Can only be 1, 3, 5, or 7. Larger values will bluir edges further before
    # detecting corners
    SOBEL_K: 3
    # The free parameter in Harris Corner Detection. Must be in range 0.04-0.06. Larger values will increase precision
    # (less false corners at the expense of missing out on more true corners as well). Smaller values increase recall
    # (miss less true corners at the expense of many more false corners)
    HARRIS_K: 0.04

  OUTPUT:
    # The folder to save the GCP txt file to.
    GCP_OUTPUT_LOC: D:/MacConnell/Final/GCPs/
    # The folder to save the georeferenced TIFF file to.
    REF_OUTPUT_LOC: D:/MacConnell/Final/Georeferenced/